-- YCB Model Import Script for CoppeliaSim
-- Generated by YCBModelImporter
-- Instructions:
-- 1. Save this as a .lua file
-- 2. In CoppeliaSim: Scripts → Load script
-- 3. Select this file and run

function importYCBModels()
    -- Get current scene
    local sceneHandle = sim.getObject('.')

    -- Create YCB models container
    local ycbContainer = sim.createPureShape(0, 0, {0.1, 0.1, 0.1}, 0, nil)
    sim.setObjectName(ycbContainer, 'YCB_Models')
    sim.setObjectInt32Parameter(ycbContainer, sim.objintparam_visibility_layer, 0)

    -- Import models
    -- Import Master Chef Can
    local 002_master_chef_can = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/002_master_chef_can/textured.obj', 0, 0, 0)
    if 002_master_chef_can ~= -1 then
        sim.setObjectName(002_master_chef_can, 'Master Chef Can')
        sim.setObjectParent(002_master_chef_can, ycbContainer, true)
        print('✅ Imported: Master Chef Can')
    else
        print('❌ Failed to import: Master Chef Can')
    end
    -- Import Cracker Box
    local 003_cracker_box = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/003_cracker_box/textured.obj', 0, 0, 0)
    if 003_cracker_box ~= -1 then
        sim.setObjectName(003_cracker_box, 'Cracker Box')
        sim.setObjectParent(003_cracker_box, ycbContainer, true)
        print('✅ Imported: Cracker Box')
    else
        print('❌ Failed to import: Cracker Box')
    end
    -- Import Sugar Box
    local 004_sugar_box = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/004_sugar_box/textured.obj', 0, 0, 0)
    if 004_sugar_box ~= -1 then
        sim.setObjectName(004_sugar_box, 'Sugar Box')
        sim.setObjectParent(004_sugar_box, ycbContainer, true)
        print('✅ Imported: Sugar Box')
    else
        print('❌ Failed to import: Sugar Box')
    end

    print('🎉 YCB model import completed!')
    print('📁 Models are organized under YCB_Models container')
end

-- Run import
importYCBModels()