-- YCB Model Import Script for CoppeliaSim
-- Generated by YCBModelImporter
-- Instructions:
-- 1. Save this as a .lua file
-- 2. In CoppeliaSim: Scripts → Load script
-- 3. Select this file and run

function importYCBModels()
    -- Get current scene
    local sceneHandle = sim.getObject('.')

    -- Create YCB models container
    local ycbContainer = sim.createPureShape(0, 0, {0.1, 0.1, 0.1}, 0, nil)
    sim.setObjectName(ycbContainer, 'YCB_Models')
    sim.setObjectInt32Parameter(ycbContainer, sim.objintparam_visibility_layer, 0)

    -- Import models
    -- Import Extra Large Clamp
    local 052_extra_large_clamp = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/052_extra_large_clamp/textured.obj', 0, 0, 0)
    if 052_extra_large_clamp ~= -1 then
        sim.setObjectName(052_extra_large_clamp, 'Extra Large Clamp')
        sim.setObjectParent(052_extra_large_clamp, ycbContainer, true)
        print('✅ Imported: Extra Large Clamp')
    else
        print('❌ Failed to import: Extra Large Clamp')
    end
    -- Import Power Drill
    local 035_power_drill = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/035_power_drill/textured.obj', 0, 0, 0)
    if 035_power_drill ~= -1 then
        sim.setObjectName(035_power_drill, 'Power Drill')
        sim.setObjectParent(035_power_drill, ycbContainer, true)
        print('✅ Imported: Power Drill')
    else
        print('❌ Failed to import: Power Drill')
    end
    -- Import Gelatin Box
    local 009_gelatin_box = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/009_gelatin_box/textured.obj', 0, 0, 0)
    if 009_gelatin_box ~= -1 then
        sim.setObjectName(009_gelatin_box, 'Gelatin Box')
        sim.setObjectParent(009_gelatin_box, ycbContainer, true)
        print('✅ Imported: Gelatin Box')
    else
        print('❌ Failed to import: Gelatin Box')
    end
    -- Import Tomato Soup Can
    local 005_tomato_soup_can = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/005_tomato_soup_can/textured.obj', 0, 0, 0)
    if 005_tomato_soup_can ~= -1 then
        sim.setObjectName(005_tomato_soup_can, 'Tomato Soup Can')
        sim.setObjectParent(005_tomato_soup_can, ycbContainer, true)
        print('✅ Imported: Tomato Soup Can')
    else
        print('❌ Failed to import: Tomato Soup Can')
    end
    -- Import Potted Meat Can
    local 010_potted_meat_can = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/010_potted_meat_can/textured.obj', 0, 0, 0)
    if 010_potted_meat_can ~= -1 then
        sim.setObjectName(010_potted_meat_can, 'Potted Meat Can')
        sim.setObjectParent(010_potted_meat_can, ycbContainer, true)
        print('✅ Imported: Potted Meat Can')
    else
        print('❌ Failed to import: Potted Meat Can')
    end
    -- Import Sugar Box
    local 004_sugar_box = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/004_sugar_box/textured.obj', 0, 0, 0)
    if 004_sugar_box ~= -1 then
        sim.setObjectName(004_sugar_box, 'Sugar Box')
        sim.setObjectParent(004_sugar_box, ycbContainer, true)
        print('✅ Imported: Sugar Box')
    else
        print('❌ Failed to import: Sugar Box')
    end
    -- Import Banana
    local 011_banana = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/011_banana/textured.obj', 0, 0, 0)
    if 011_banana ~= -1 then
        sim.setObjectName(011_banana, 'Banana')
        sim.setObjectParent(011_banana, ycbContainer, true)
        print('✅ Imported: Banana')
    else
        print('❌ Failed to import: Banana')
    end
    -- Import Cracker Box
    local 003_cracker_box = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/003_cracker_box/textured.obj', 0, 0, 0)
    if 003_cracker_box ~= -1 then
        sim.setObjectName(003_cracker_box, 'Cracker Box')
        sim.setObjectParent(003_cracker_box, ycbContainer, true)
        print('✅ Imported: Cracker Box')
    else
        print('❌ Failed to import: Cracker Box')
    end
    -- Import Large Clamp
    local 051_large_clamp = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/051_large_clamp/textured.obj', 0, 0, 0)
    if 051_large_clamp ~= -1 then
        sim.setObjectName(051_large_clamp, 'Large Clamp')
        sim.setObjectParent(051_large_clamp, ycbContainer, true)
        print('✅ Imported: Large Clamp')
    else
        print('❌ Failed to import: Large Clamp')
    end
    -- Import Bleach Cleanser
    local 021_bleach_cleanser = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/021_bleach_cleanser/textured.obj', 0, 0, 0)
    if 021_bleach_cleanser ~= -1 then
        sim.setObjectName(021_bleach_cleanser, 'Bleach Cleanser')
        sim.setObjectParent(021_bleach_cleanser, ycbContainer, true)
        print('✅ Imported: Bleach Cleanser')
    else
        print('❌ Failed to import: Bleach Cleanser')
    end
    -- Import Pitcher Base
    local 019_pitcher_base = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/019_pitcher_base/textured.obj', 0, 0, 0)
    if 019_pitcher_base ~= -1 then
        sim.setObjectName(019_pitcher_base, 'Pitcher Base')
        sim.setObjectParent(019_pitcher_base, ycbContainer, true)
        print('✅ Imported: Pitcher Base')
    else
        print('❌ Failed to import: Pitcher Base')
    end
    -- Import Scissors
    local 037_scissors = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/037_scissors/textured.obj', 0, 0, 0)
    if 037_scissors ~= -1 then
        sim.setObjectName(037_scissors, 'Scissors')
        sim.setObjectParent(037_scissors, ycbContainer, true)
        print('✅ Imported: Scissors')
    else
        print('❌ Failed to import: Scissors')
    end
    -- Import Large Marker
    local 040_large_marker = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/040_large_marker/textured.obj', 0, 0, 0)
    if 040_large_marker ~= -1 then
        sim.setObjectName(040_large_marker, 'Large Marker')
        sim.setObjectParent(040_large_marker, ycbContainer, true)
        print('✅ Imported: Large Marker')
    else
        print('❌ Failed to import: Large Marker')
    end
    -- Import Bowl
    local 024_bowl = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/024_bowl/textured.obj', 0, 0, 0)
    if 024_bowl ~= -1 then
        sim.setObjectName(024_bowl, 'Bowl')
        sim.setObjectParent(024_bowl, ycbContainer, true)
        print('✅ Imported: Bowl')
    else
        print('❌ Failed to import: Bowl')
    end
    -- Import Pudding Box
    local 008_pudding_box = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/008_pudding_box/textured.obj', 0, 0, 0)
    if 008_pudding_box ~= -1 then
        sim.setObjectName(008_pudding_box, 'Pudding Box')
        sim.setObjectParent(008_pudding_box, ycbContainer, true)
        print('✅ Imported: Pudding Box')
    else
        print('❌ Failed to import: Pudding Box')
    end
    -- Import Wood Block
    local 036_wood_block = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/036_wood_block/textured.obj', 0, 0, 0)
    if 036_wood_block ~= -1 then
        sim.setObjectName(036_wood_block, 'Wood Block')
        sim.setObjectParent(036_wood_block, ycbContainer, true)
        print('✅ Imported: Wood Block')
    else
        print('❌ Failed to import: Wood Block')
    end
    -- Import Mug
    local 025_mug = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/025_mug/textured.obj', 0, 0, 0)
    if 025_mug ~= -1 then
        sim.setObjectName(025_mug, 'Mug')
        sim.setObjectParent(025_mug, ycbContainer, true)
        print('✅ Imported: Mug')
    else
        print('❌ Failed to import: Mug')
    end
    -- Import Mustard Bottle
    local 006_mustard_bottle = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/006_mustard_bottle/textured.obj', 0, 0, 0)
    if 006_mustard_bottle ~= -1 then
        sim.setObjectName(006_mustard_bottle, 'Mustard Bottle')
        sim.setObjectParent(006_mustard_bottle, ycbContainer, true)
        print('✅ Imported: Mustard Bottle')
    else
        print('❌ Failed to import: Mustard Bottle')
    end
    -- Import Master Chef Can
    local 002_master_chef_can = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/002_master_chef_can/textured.obj', 0, 0, 0)
    if 002_master_chef_can ~= -1 then
        sim.setObjectName(002_master_chef_can, 'Master Chef Can')
        sim.setObjectParent(002_master_chef_can, ycbContainer, true)
        print('✅ Imported: Master Chef Can')
    else
        print('❌ Failed to import: Master Chef Can')
    end
    -- Import Tuna Fish Can
    local 007_tuna_fish_can = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/007_tuna_fish_can/textured.obj', 0, 0, 0)
    if 007_tuna_fish_can ~= -1 then
        sim.setObjectName(007_tuna_fish_can, 'Tuna Fish Can')
        sim.setObjectParent(007_tuna_fish_can, ycbContainer, true)
        print('✅ Imported: Tuna Fish Can')
    else
        print('❌ Failed to import: Tuna Fish Can')
    end
    -- Import Foam Brick
    local 061_foam_brick = sim.importShape(0, '../../Data_sets/YCB-Video-Base/models/061_foam_brick/textured.obj', 0, 0, 0)
    if 061_foam_brick ~= -1 then
        sim.setObjectName(061_foam_brick, 'Foam Brick')
        sim.setObjectParent(061_foam_brick, ycbContainer, true)
        print('✅ Imported: Foam Brick')
    else
        print('❌ Failed to import: Foam Brick')
    end

    print('🎉 YCB model import completed!')
    print('📁 Models are organized under YCB_Models container')
end

-- Run import
importYCBModels()